testing = "Login flow"
case = "User is anonymous and makes an attempt to login"

[api]
url = ""
method = "POST"

# Single request scenario
[params]
username = "username"
password = "password"

[headers]
x-some-header = "header value"

[response]
response = { contains = "Login successful" }

## Multi request scenario example
[request]
expect = "a"

[request]
expect = "b"

[request]
expect = "c"
