testing = "Login flow"
case = "User is anonymous and makes an attempt to login"

[api]
url = ""
method = "POST"

[params]
username = "username"
password = "password"

[headers]
x-some-header = "header value"

[response]
response = { contains = "Login successful" }
